### ISSUE TITLE
Codepen link shows up as undefined

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio-apps/reactivesearch-onboarding#1]
On the final step of the tutorial, when one clicks on the codepen link, it comes up as undefined.

![](https://i.imgur.com/Wxq95kd.png)

* Codepen link - does not show any code

![](https://i.imgur.com/G7xld1m.png)

#### Relevant console logs

![](https://i.imgur.com/Pglhkh2.png)

**Comment by metagrover** [comment]
Fix to be replicated: https://github.com/appbaseio-apps/airbeds-onboarding/commit/71ec41bfecc75b3dde2ce19b89be1dc29893e123
